import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  styleSidebar: [
    'intro',
    {
      type: 'category',
      label: '视觉表现 · Visual Styles',
      collapsed: false,
      link: { type: 'doc', id: 'styles/visual/index' },
      items: [
        'styles/visual/minimalism',
        'styles/visual/memphis',
        'styles/visual/neumorphism',
        'styles/visual/glassmorphism',
        'styles/visual/cyberpunk',
        'styles/visual/vaporwave',
        'styles/visual/pixel-retro',
        'styles/visual/swiss-design',
        'styles/visual/bauhaus',
        'styles/visual/art-deco',
      ],
    },
    {
      type: 'category',
      label: '东方古典 · Eastern Classical',
      collapsed: false,
      link: { type: 'doc', id: 'styles/eastern/index' },
      items: [
        'styles/eastern/chinese-ink',
        'styles/eastern/japanese-zen',
        'styles/eastern/ukiyo-e',
        'styles/eastern/arabic-geometric',
        'styles/eastern/indian-mehndi',
        'styles/eastern/tang-pattern',
        'styles/eastern/blue-white-porcelain',
      ],
    },
    {
      type: 'category',
      label: '配色方案 · Color Schemes',
      collapsed: false,
      link: { type: 'doc', id: 'styles/color/index' },
      items: [
        'styles/color/morandi',
        'styles/color/macaron',
        'styles/color/earth-tone',
        'styles/color/neon',
        'styles/color/monochrome',
        'styles/color/film-retro',
        'styles/color/pastel',
      ],
    },
    {
      type: 'category',
      label: '字体排版 · Typography',
      collapsed: false,
      link: { type: 'doc', id: 'styles/typography/index' },
      items: [
        'styles/typography/serif-classic',
        'styles/typography/sans-modern',
        'styles/typography/hand-written',
        'styles/typography/pixel-font',
        'styles/typography/chinese-kai',
        'styles/typography/monospace',
      ],
    },
    {
      type: 'category',
      label: '时代年代 · Era',
      collapsed: false,
      link: { type: 'doc', id: 'styles/era/index' },
      items: [
        'styles/era/y2k',
        'styles/era/psychedelic-60s',
        'styles/era/retro-80s',
        'styles/era/grunge-90s',
        'styles/era/disco-70s',
        'styles/era/mtv-90s',
      ],
    },
    {
      type: 'category',
      label: '材质纹理 · Material',
      collapsed: false,
      link: { type: 'doc', id: 'styles/material/index' },
      items: [
        'styles/material/paper-texture',
        'styles/material/frosted-glass',
        'styles/material/metallic',
        'styles/material/wood-grain',
        'styles/material/water-ripple',
        'styles/material/fabric',
      ],
    },
    {
      type: 'category',
      label: '现代趋势 · Modern Trends',
      collapsed: false,
      link: { type: 'doc', id: 'styles/modern/index' },
      items: [
        'styles/modern/modern-tech',
        'styles/modern/editorial',
        'styles/modern/nordic',
        'styles/modern/dark-first',
        'styles/modern/brutalism',
        'styles/modern/magazine',
        'styles/modern/flat-design',
        'styles/modern/material-design',
        'styles/modern/3d-illustration',
        'styles/modern/gradient-mesh',
      ],
    },
  ],
}

export default sidebars
